### ISSUE TITLE
两个建议😁

### ISSUE THREAD

**Issue by pdm6688** [Samge0/vscode-samge-translate#1]
1. 能否支持直接读取光标靠近的词组，比如以空格或者"等方式判断词组，这样在写代码的过程中就不用选中名称再去转换命名了。
2. 能否对所有转变量名的方法增加键盘快捷键，我们自己配置。

谢谢大佬😁😁

**Comment by Samge0** [comment]
> 1. 能否支持直接读取光标靠近的词组，比如以空格或者"等方式判断词组，这样在写代码的过程中就不用选中名称再去转换命名了。
> 2. 能否对所有转变量名的方法增加键盘快捷键，我们自己配置。
> 
> 谢谢大佬😁😁

1、我理解的意思是取光标左侧最后一个词组，配合快捷键生成变量名/函数名等，例如：`let 变量` 此时光标在“量”字后侧，根据空格切割，此时按快捷键后应该自动提取“`变量`”这两个字进行转换，转换（不同类型转换样式不同）前后的对比为：
`let 变量` => `let variable`
2、安排

**Comment by pdm6688** [comment]
是的，就是这个意思。不过可能存在很多其他情况。
比如你示例的js语言 ```let 变量``` 需要翻译的中文前面是空格
还有很多别的场景 
- python中声明是没有 ```let``` ```var``` 这种关键字的，所以前面可能也没有空格
- ```<button id="btn">中文</button>``` 此时需要翻译的中文前面是```>```
- 还有 ```"``` ```'``` 等等，😅英语不好，所以场景不只是变量。

我的想法是这是个**短词快捷翻译**的功能，执行步骤为：
1. 执行快捷键，比如替换翻译**小驼峰格式**、**正常格式**等格式。
2. 读取光标前本行的字符。
3. 执行正则提取光标前**连续**的中文。
4. 执行字符数量的判断，大于0，并通过设定的**最大字符数**限制，以防有什么bug，导致翻译内容过多。
5. 替换写入翻译的内容。

**Comment by Samge0** [comment]
好的，我先试着加一下这个【短词快捷翻译】功能；
- 侧重`短词`
- 提供自定义的`最大字符数`配置
- 同一行光标左侧`连续中文`（侧重短词而不是句子，所以标点符号这些不要）

**Comment by pdm6688** [comment]
还有快捷键哦，我只能说爱你了 -。-

**Comment by Samge0** [comment]
插件v0.0.7版本已发布，到时候更新试试。该功能默认状态为false，需要到配置中开启该功能：

![007配置](https://github.com/Samge0/vscode-samge-translate/raw/main/screenshot/KeyboardShortcutsAndZh2varNew.png)

![007配置](https://github.com/Samge0/vscode-samge-translate/raw/main/screenshot/KeyboardShortcutsAndZh2varNew.gif)

**Comment by pdm6688** [comment]
了解 我测试后 来反馈

**Comment by pdm6688** [comment]
使用了多种场景，目前没有发现任何问题。赞

**Comment by Samge0** [comment]
> 使用了多种场景，目前没有发现任何问题。赞

感谢你的反馈，在这提前祝你新年快乐~
