### ISSUE TITLE
交互体验改进建议

### ISSUE THREAD

**Issue by ls0001** [Samge0/vscode-samge-translate#3]
首先感谢提供这款功能丰富的翻译插件。希望把它开发得更加好用。
由于不是所有翻译都准确，对于需要将译文插入源文件的翻译，当前版本需要在输出窗口查看译文对比，有的翻译比较长而不容易查看。
因此建议作以下改进：
1.对于比较长的文本在右侧和Output窗口中的显示，建议排版换行。
2.添加用户交互，先输出译文显示之后由用户选择操作：
  Option1.直接替换原文
  Option2.将译文追加到原文末尾并选中译文，方便保留原文和对译文进行对照、修改、拖放或换行等。
  Option3.放弃
3.多行多句的原文翻译后（百度翻译，其它的未试）的译文应该保留句与句之间的换行符。

**Comment by Samge0** [comment]
> 首先感谢提供这款功能丰富的翻译插件。希望把它开发得更加好用。 由于不是所有翻译都准确，对于需要将译文插入源文件的翻译，当前版本需要在输出窗口查看译文对比，有的翻译比较长而不容易查看。 因此建议作以下改进： 1.对于比较长的文本在右侧和Output窗口中的显示，建议排版换行。 2.添加用户交互，先输出译文显示之后由用户选择操作： Option1.直接替换原文 Option2.将译文追加到原文末尾并选中译文，方便保留原文和对译文进行对照、修改、拖放或换行等。 Option3.放弃 3.多行多句的原文翻译后（百度翻译，其它的未试）的译文应该保留句与句之间的换行符。

感谢仁兄的建议，最近我比较虚，后续有时间再尝试跟进一下哈

**Comment by Samge0** [comment]
hi，相关功能已在`0.0.8`版本中追加，可以在vscode中将插件更新到`0.0.8`版本试试看。
![vscode-samge](https://github.com/Samge0/vscode-samge-translate/assets/17336101/43cf825e-600a-47d1-9bf4-813723770287)
