### ISSUE TITLE
适合什么版本

### ISSUE THREAD

**Issue by cute-angelia** [Samge0/vscode-samge-translate#9]
你好，提示 

> 无法安装“samge.vscode-samge-translate”扩展，因为它与当前 Visual Studio Code 版本不兼容(版本 1.82.2)。

**Comment by Samge0** [comment]
你好，[插件配置](https://github.com/Samge0/vscode-samge-translate/blob/main/package.json) 中指定` "engines": { "vscode": "^1.85.0" }`，要求 VSCode 的版本是 `1.85.0 或更高版本`
